[package]
name = "dissimetrics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.7"
ndarray = "0.15"
eframe = "0.27"
rfd = "0.12.0"